// <auto-generated />
using ActivityTrackerPC.Writer.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActivityTrackerPC.Migrations
{
    [DbContext(typeof(ActivityTrackerContext))]
    [Migration("20221007121035_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ActivityTrackerPC.Writer.DB.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ApplicationId");

                    b.ToTable("application");
                });

            modelBuilder.Entity("ActivityTrackerPC.Writer.DB.ApplicationDuration", b =>
                {
                    b.Property<int>("ApplicationDurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<long?>("Duration")
                        .HasColumnType("bigint");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationDurationId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("SessionId");

                    b.ToTable("applicationDurations");
                });

            modelBuilder.Entity("ActivityTrackerPC.Writer.DB.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("sessions");
                });

            modelBuilder.Entity("ActivityTrackerPC.Writer.DB.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("UserName")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ActivityTrackerPC.Writer.DB.ApplicationDuration", b =>
                {
                    b.HasOne("ActivityTrackerPC.Writer.DB.Application", "Application")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ActivityTrackerPC.Writer.DB.Session", "Session")
                        .WithMany("Applications")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ActivityTrackerPC.Writer.DB.Session", b =>
                {
                    b.HasOne("ActivityTrackerPC.Writer.DB.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ActivityTrackerPC.Writer.DB.Application", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("ActivityTrackerPC.Writer.DB.Session", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("ActivityTrackerPC.Writer.DB.User", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
